version: '3.4'
services:
  datetimegin:
    container_name: datetimeginapp
    build:
      context: ./
      dockerfile: DockerFile-gin
      target: datetimeservergin
    ports:
      - "8091:8090"

  datetimehttp:
    container_name: datetimehttpapp
    build:
      context: ./
      dockerfile: DockerFile-http
      target: datetimeserverhttp
    ports:
      - "8090:8090"
