# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "development" ]
  pull_request:
    branches: [ "main" ]

jobs:

  Check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22.4'

    - name: Run golangci-lint in datetimegin
      uses: golangci/golangci-lint-action@v3
      with:
        working-directory: datetimegin
  
    - name: Run golangci-lint in datetimehttp
      uses: golangci/golangci-lint-action@v3
      with:
        working-directory: datetimehttp
    
    - name: Run go fmt in datetimegin
      uses: Jerome1337/gofmt-action@v1.0.5
      with:
        gofmt-path: './datetimegin/'

    - name: Run go fmt datetimehttp
      uses: Jerome1337/gofmt-action@v1.0.5
      with:
        gofmt-path: './datetimehttp'

    - name: Test
      run: |
        cd datetimegin && go test -v ./...
        cd ../datetimehttp && go test -v ./...

    
    

    